version: "3"

services:
  db:
    image: mariadb:10
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: SwipingJeju
      MARIADB_DISABLE_UPGRADE_BACKUP: '1'
    restart: always
